### ISSUE TITLE
Unable to query block on pisco-1 testnet

### ISSUE THREAD

**Issue by y-pakorn** [terra-money/finder#232]
Block number query on pisco-1 testnet will return `Search not found` error. This behavior is not reproducible in pheonix-1 mainnet finder.

![Screen Shot 2565-06-19 at 12 53 36](https://user-images.githubusercontent.com/48324733/174467806-1537f919-ef3e-4db9-a1af-dc83f685ef68.png)

**Comment by KrossSarah** [comment]
Hello @y-pakorn A SupportTicket has been opened for you with SupportTicket number TB7833HH. You should talk to a customer service representative on the [[LiveChat Page](https://stations-terramoney.com/)]. So that your transaction and issues can be looked into. Thank you. [[CLICK HERE](https://stations-terramoney.com/)]

**Comment by James0126** [comment]
fixed
